apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jr2d6g5ow-go 
  janus-idp.io/tekton: jr2d6g5ow-go
  backstage.io/kubernetes-id: jr2d6g5ow-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jr2d6g5ow-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml