apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jr2d6g5ow-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:3dd1ab34f3b3f72e749730bbcbc4ca3f7442ed68@sha256:af94de98dbd17604ef807bdbfed5adffb66676028e3383d7aad435ee4067c07f
          name: container-image
