apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jr2d6g5ow-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jr2d6g5ow-go 
  name: jr2d6g5ow-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jr2d6g5ow-go 
